config/routes.rb
Rails.application.routes.draw do
  get 'plant_tags/new'
  get 'plant_tags/create'
  get 'plants/new'
  get 'plants/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'gardens#index'
  resources :gardens, only: [:show] do
    resources :plants, only: [:new, :create]
  end

  resources :plants, only: [:destroy] do
    resources :plant_tags, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  has_many :plants, dependent: :destroy
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden
  has_many :plant_tags
  has_many :tags, through: :plant_tags
end

app/models/plant_tag.rb
class PlantTag < ApplicationRecord
  belongs_to :plant
  belongs_to :tag
  validates :tag, uniqueness: { scope: :plant }
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :plant_tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  def index
    @gardens = Garden.all
  end

  def show
    @garden = Garden.find(params[:id])
  end
end

app/controllers/plant_tags_controller.rb
class PlantTagsController < ApplicationController
  def new
    @plant = Plant.find(params[:plant_id])
    @plant_tag = PlantTag.new
  end

  def create
    @plant = Plant.find(params[:plant_id])
    @tags = Tag.where(id: tag_params)
    @tags.each do |tag|
      PlantTag.create(tag: tag, plant: @plant)
    end
    redirect_to garden_path(@plant.garden)
  end

  private

  def tag_params
    params.require(:plant_tag).require(:tag)
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def new
    @garden = Garden.find(params[:garden_id])
    @plant = Plant.new
  end

  def create
    @plant = Plant.new(plant_params)
    @garden = Garden.find(params[:garden_id])
    @plant.garden = @garden
    if @plant.save
      redirect_to garden_path(@garden)
    else
      render :new
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy
    redirect_to garden_path(@plant.garden)
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plant_tags_helper.rb
module PlantTagsHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/index.html.erb
<h1>Gardens#index</h1>

<ul>
  <% @gardens.each do |garden| %>
    <li>
    <%= link_to "#{garden.name}", garden_path(garden) %>
    </li>
  <% end %>
</ul>

app/views/gardens/show.html.erb
<div style="background-image: url(<%= @garden.image_url %>); height: 40vh;">
<h1 style="background: black; color: white;"><%= @garden.name %></h1>
</div>

<p>Description: <%= @garden.description %></p>
<p>Surface: <%= @garden.surface %>m²</p>

<h2> My plants </h2>
<div class='plants-container'>
  <% @garden.plants.each do |plant| %>
    <div class='plant-card'>
      <div class="card-tags">
        <% plant.tags.each do |tag| %>
          <%= tag.name %>
        <% end %>
        <%= link_to '+', new_plant_plant_tag_path(plant) %>
      </div>
      <img src= <%= plant.image_url %> />
      <%= plant.name %>
      <%= link_to 'Destroy this plant', plant_path(plant), method: :delete, data: { confirm: "Are you sure ?" } %>
    </div>
  <% end %>
</div>
<%= link_to 'Add a plant', new_garden_plant_path(@garden) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GardenParadise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plant_tags/new.html.erb
<h1>Ajouter un tag à la plante <%= @plant.name %></h1>

<%= simple_form_for [@plant, @plant_tag] do |f| %>
  <%= f.input :tag, collection: Tag.all, input_html: {multiple: true, class: 'select2-plant-tags' }, include_hidden: false %>
  <%= f.submit %>
<% end %>

app/views/plants/new.html.erb
<%= simple_form_for([@garden, @plant]) do |f| %>
  <%= f.input :name %>
  <%= f.input :image_url %>
  <%= f.submit %>
<% end %>